import React, { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import {
    Plus, Search, MessageSquare, Shield, ChevronDown,
    Paperclip, Settings, CheckCircle,
    Code, Briefcase, Globe, Lock,
    BarChart3, Key, WifiOff, ChevronRight,
    Hash, Sparkles, Bot,
    PanelLeftClose, PanelLeft, ArrowUp, X,
    Sun, Moon,
    Loader2, AlertCircle, FileText, RefreshCw
} from 'lucide-react';
import './agentTheme.css';
import { useAgent } from '../hooks/useAgent';
import type { AgentTool } from '../hooks/useAgent';
import type { MessageEvent } from '../agents/types';
import { ToolManager } from './ToolManager';
import { MCPManager } from './MCPManager';
import { SkillsManager } from './SkillsManager';
import { chatHistoryService } from '../services/chatHistoryService';
import { licensingService, type LicenseInfo } from '../services/licensingService';
import { dockerAgentService, type AgentStreamEvent } from '../services/dockerAgentService';
import { postProcessAgentResponse } from '../utils/trustchainPostProcess';

// Hooks
import { useChatState } from '../hooks/useChatState';
import { useTaskQueue } from '../hooks/useTaskQueue';

// Services
import { agentCallbacksService } from '../services/agents/agentCallbacksService';
import { trustchainService } from '../services/trustchainService';

// Extracted components
import type { ThemeMode, Tier, Artifact, Message, Conversation } from './components/types';
import {
    ARTIFACT_META, TierBadge, AGENT_TOOLS, AGENT_POLICIES, DEMO_CONVERSATIONS,
} from './components/constants';
import { MessageBubble } from './components/MessageBubble';
import { ArtifactsPanel } from './components/ArtifactsPanel';
import ProSettingsPanel from './components/ProSettingsPanel';
import { ChatSidebar } from './components/ChatSidebar';
import { ChatHeader } from './components/ChatHeader';
import { ChatArea } from './components/ChatArea';
import { InputPanel } from './components/InputPanel';
import { ChainStatusBar } from './components/ChainStatusBar';

/* Types imported from ./components/types */

/* ═══════════════════════════════════════════
   Demo Artifacts
   ═══════════════════════════════════════════ */

const DEMO_ARTIFACTS: Record<string, Artifact> = {
    'art-security': {
        id: 'art-security',
        type: 'report',
        title: 'Security Analysis Report',
        content: `# Security Analysis — Commit a7f3b2c

## Summary
Scanned 14 files across 3 modules. Found **1 warning**, 0 critical issues.

## Results

| Check | Status | Severity | Details |
|-------|--------|----------|---------|
| SQL Injection | ✅ Safe | — | Parameterized queries in all 8 endpoints |
| XSS | ✅ Safe | — | Output escaped via \`sanitizeHtml()\` |
| Auth Bypass | ✅ Safe | — | JWT validation on all protected routes |
| CSRF | ✅ Safe | — | SameSite cookies + CSRF tokens |
| Dependency Vulns | ⚠️ Warning | Medium | \`lodash@4.17.20\` → CVE-2021-23337 |

## Recommendation
\`\`\`bash
npm install lodash@4.17.21
\`\`\`

## Verification Chain
All operations in this analysis are cryptographically signed. Chain hash: \`a7f3b2c8e91d4506\`.

---
*Generated by TrustChain Agent v0.3.0 — Ed25519 signed*`,
        createdAt: new Date(Date.now() - 90000),
        signature: 'a7f3b2c8e91d4506f8a2e3b1c9d0f5a6',
        version: 1,
    },
    'art-compliance': {
        id: 'art-compliance',
        type: 'report',
        title: 'SOC 2 Compliance Report',
        content: `# SOC 2 Type II Compliance Report

**Organization:** TrustChain Agent Session
**Period:** ${new Date().toLocaleDateString()}
**Overall Score: 100%** ✅ Compliant

---

## Trust Services Criteria

### CC6.1 — Logical and Physical Access Controls
| Control | Status | Evidence |
|---------|--------|----------|
| Key Management | ✅ Pass | Ed25519 keys with AES-256-GCM encryption |
| Access Logging | ✅ Pass | All API calls logged with caller identity |
| Session Management | ✅ Pass | Token-based auth with 15min expiry |

### CC7.2 — System Monitoring
| Control | Status | Evidence |
|---------|--------|----------|
| Cryptographic Signing | ✅ Pass | All 3 tool operations signed |
| Chain Integrity | ✅ Pass | Parent-child Merkle chain verified |
| Anomaly Detection | ✅ Pass | 0 violations in 47 operations |

### CC8.1 — Change Management
| Control | Status | Evidence |
|---------|--------|----------|
| Audit Trail | ✅ Pass | Complete chain of trust maintained |
| Nonce Protection | ✅ Pass | Replay attacks blocked (nonce store active) |
| Version Control | ✅ Pass | All artifacts versioned and signed |

---

## Certification
This report was generated automatically by TrustChain Pro v0.3.0.
All data points are backed by cryptographic signatures verifiable through the chain of trust.

**Report Hash:** \`d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9\`
**Signed:** Ed25519 by key \`key_prod_001\``,
        createdAt: new Date(Date.now() - 30000),
        signature: 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9',
        version: 1,
    },
    'art-code': {
        id: 'art-code',
        type: 'code',
        title: 'auth-middleware.ts',
        language: 'typescript',
        content: `import { Request, Response, NextFunction } from 'express';
import { TrustChain, Ed25519Signer } from 'trustchain';
import jwt from 'jsonwebtoken';

const chain = new TrustChain({ signer: new Ed25519Signer() });

/**
 * Authentication middleware with TrustChain verification.
 * Every authenticated request is signed into the chain of trust.
 */
export async function authMiddleware(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  const token = req.headers.authorization?.replace('Bearer ', '');

  if (!token) {
    res.status(401).json({ error: 'Missing authorization token' });
    return;
  }

  try {
    // Verify JWT
    const decoded = jwt.verify(token, process.env.JWT_SECRET!);

    // Sign the authenticated request into TrustChain
    const entry = await chain.sign({
      action: 'api_request',
      method: req.method,
      path: req.path,
      userId: (decoded as any).sub,
      timestamp: new Date().toISOString(),
    });

    // Attach to request for downstream use
    req.trustChainEntry = entry;
    req.user = decoded;

    // Verify chain integrity
    const isValid = await chain.verifyChain();
    if (!isValid) {
      console.error('⚠️ Chain integrity violation detected!');
      // Log but don't block — alert the security team
      await alertSecurityTeam(entry);
    }

    next();
  } catch (error) {
    res.status(403).json({ error: 'Invalid or expired token' });
  }
}

async function alertSecurityTeam(entry: any): Promise<void> {
  // Send to monitoring system
  console.log(\`🚨 Violation: \${JSON.stringify(entry)}\`);
}`,
        createdAt: new Date(Date.now() - 60000),
        signature: 'c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8',
        version: 2,
    },
    'art-plan': {
        id: 'art-plan',
        type: 'plan',
        title: 'Implementation Plan',
        content: `# Migration to TrustChain v3.0

## Phase 1: Core Migration (Week 1-2)
- [ ] Update \`trustchain\` package to v3.0
- [ ] Migrate from RSA to Ed25519 signing
- [ ] Update key management to use new KMS API
- [x] Audit existing chain for compatibility

## Phase 2: Integration (Week 3)
- [ ] Update all middleware to use new chain API
- [ ] Add compliance hooks to CI/CD pipeline
- [ ] Configure air-gapped fallback for offline envs

## Phase 3: Verification (Week 4)
- [ ] Run full regression test suite
- [ ] Generate compliance reports (SOC2, HIPAA)
- [ ] Create migration documentation
- [ ] Deploy to staging with canary release

## Risk Assessment
| Risk | Impact | Mitigation |
|------|--------|------------|
| Chain break during migration | High | Dual-write to old + new chains |
| Key rotation failure | Medium | Backup keys in HSM |
| Performance regression | Low | Benchmark before/after |

## Dependencies
- \`trustchain@3.0.0\` (not yet released)
- \`trustchain-pro@0.4.0\` for compliance module
- Node.js ≥20 for Ed25519 native support`,
        createdAt: new Date(Date.now() - 45000),
        signature: 'e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0',
        version: 3,
    },
    'art-graph': {
        id: 'art-graph',
        type: 'graph' as const,
        title: 'Execution Graph',
        tier: 'pro' as Tier,
        content: `# Execution Graph — Session a7f3b2c

## Graph Statistics
| Metric | Value |
|--------|-------|
| Total Nodes | 6 |
| Root Chains | 2 |
| Max Depth | 3 |
| Forks Detected | 0 |
| Replays Detected | 0 |
| Orphans | 0 |

## DAG Visualization
\`\`\`
git_diff [a7f3b2c] ──→ security_scan [c9d0e1f] ──→ verify_chain [b5a6c7d]
                                                       │
                                                       └──→ code_generate [a1b2c3d]
                                                                │
compiance_evaluate [e1f2a3b] ──→ export_pdf [f5a6b7c]
\`\`\`

## Fork Analysis
No forks detected — all execution paths are linear. This indicates deterministic agent behavior with no branching decisions.

## Replay Detection
No replay attacks detected. All nonces are unique across the session.

## Integrity
All 6 nodes verified. Parent-child signature chain is intact.

---
*Generated by ExecutionGraph (TrustChain Pro) — DAG Forensics Module*`,
        createdAt: new Date(Date.now() - 25000),
        signature: 'g7h8i9j0k1l2m3n4o5p6q7r8',
        version: 1,
    },
    'art-analytics': {
        id: 'art-analytics',
        type: 'analytics' as const,
        title: 'Analytics Dashboard',
        tier: 'pro' as Tier,
        content: `# TrustChain Analytics — Live Snapshot

## Operations Summary
| Metric | Value |
|--------|-------|
| Total Operations | 47 |
| Verified | 47 (100%) |
| Failed | 0 |
| Policy Violations | 0 |
| Unique Tools | 6 |
| Active Chains | 2 |
| Throughput | 9,100 ops/sec |

## Tool Performance
| Tool | Calls | Avg Latency | Errors |
|------|-------|-------------|--------|
| verify_chain | 12 | 0.11ms | 0 |
| security_scan | 8 | 2.3ms | 0 |
| code_generate | 6 | 410ms | 0 |
| compliance_evaluate | 5 | 85ms | 0 |
| git_diff | 9 | 45ms | 0 |
| export_pdf | 7 | 320ms | 0 |

## Signature Performance
| Metric | Value | Target |
|--------|-------|--------|
| Sign Latency | 0.11ms | < 2.0ms |
| Verify Latency | 0.22ms | < 2.0ms |
| Storage Overhead | 124 bytes | < 200 bytes |

---
*Powered by TrustChainAnalytics (Pro) — Real-time signing analytics*`,
        createdAt: new Date(Date.now() - 20000),
        signature: 's1t2u3v4w5x6y7z8a9b0c1d2',
        version: 1,
    },
};

/* ═══════════════════════════════════════════
   Demo Data
   ═══════════════════════════════════════════ */

/* DEMO_CONVERSATIONS imported from ./components/constants */

const DEMO_MESSAGES: Message[] = [
    {
        id: 'm1',
        role: 'user',
        content: 'Run a full security audit on the auth module and generate compliance reports. Check everything.',
        timestamp: new Date(Date.now() - 120000),
    },
    {
        id: 'm2',
        role: 'assistant',
        content: `Audit complete. Scanned **14 files**, found **1 CVE** (lodash@4.17.20 → CVE-2021-23337, Medium). All 8 SOC 2 controls passed. Chain integrity verified across all 7 operations — no forks, replays, or orphans detected.`,
        timestamp: new Date(Date.now() - 90000),
        signature: 'a7f3b2c8e91d4506f8a2e3b1c9d0f5a6e7b8c9d0',
        verified: true,
        artifactIds: ['art-security', 'art-graph', 'art-compliance'],
        executionSteps: [
            {
                id: 'es1', type: 'planning', label: 'Planning',
                detail: 'Plan: scan code → audit deps → verify chain → build graph → compliance report',
                latencyMs: 45,
            },
            {
                id: 'es2', type: 'tool', label: 'Scan Code',
                toolName: 'tc_git_diff', tier: 'oss', signed: true, latencyMs: 45,
                args: { commit: 'HEAD~1' }, result: '14 files changed',
                signature: '3f8a1b2c',
            },
            {
                id: 'es3', type: 'tool', label: 'Security Scan',
                toolName: 'tc_security_scan', tier: 'oss', signed: true, latencyMs: 230,
                args: { depth: 'full', modules: ['auth', 'api', 'core'] },
                result: '1 warning: lodash CVE-2021-23337',
                signature: 'c9d0e1f2',
            },
            {
                id: 'es4', type: 'tool', label: 'Verify Chain',
                toolName: 'tc_verify_chain', tier: 'oss', signed: true, latencyMs: 12,
                args: {}, result: 'Chain valid, 3 nodes',
                signature: 'b5a6c7d8',
            },
            {
                id: 'es5', type: 'tool', label: 'Build Execution Graph',
                toolName: 'tc_execution_graph', tier: 'pro', signed: true, latencyMs: 18,
                args: { session: 'current' }, result: '3 nodes, 1 chain, 0 forks',
                signature: 'h1i2j3k4',
            },
            {
                id: 'es6', type: 'tool', label: 'Compliance Evaluate',
                toolName: 'tc_compliance_report', tier: 'enterprise', signed: true, latencyMs: 85,
                args: { framework: 'soc2', type: 'type_ii' },
                result: 'SOC 2 score: 100% (8/8 controls)',
                signature: 'e1f2a3b4',
            },
            {
                id: 'es7', type: 'artifacts', label: 'Artifacts Generated',
                artifactIds: ['art-security', 'art-graph', 'art-compliance'],
            },
        ],
    },
    {
        id: 'm3',
        role: 'user',
        content: 'Show me the analytics dashboard for this session.',
        timestamp: new Date(Date.now() - 40000),
    },
    {
        id: 'm4',
        role: 'assistant',
        content: `Analytics snapshot generated. **9,100 ops/sec** throughput with **0.11ms** average signing latency. All 47 operations verified successfully across this session.`,
        timestamp: new Date(Date.now() - 35000),
        signature: 's1t2u3v4w5x6y7z8a9b0c1d2e3f4g5h6',
        verified: true,
        artifactId: 'art-analytics',
        executionSteps: [
            {
                id: 'es8', type: 'tool', label: 'Analytics Snapshot',
                toolName: 'tc_analytics_snapshot', tier: 'pro', signed: true, latencyMs: 3,
                args: {}, result: '47 ops, 100% verified',
                signature: 'p1q2r3s4',
            },
        ],
    },
];

/* ═══════════════════════════════════════════
   Subcomponents imported from ./components/
   (ThinkingContainer, MessageBubble, ArtifactCard,
    ArtifactsPanel, TierBadge, MarkdownRenderer, etc.)
   ═══════════════════════════════════════════ */

/* ═══════════════════════════════════════════
   Main App
   ═══════════════════════════════════════════ */

const HostSimulatorMode: React.FC = () => {
    const iframeRef = useRef<HTMLIFrameElement | null>(null);
    const [ready, setReady] = useState(false);
    const [documentMode, setDocumentMode] = useState<'level1' | 'level2'>('level2');

    useEffect(() => {
        const handler = (e: any) => {
            if (!e.data || typeof e.data !== 'object') return;
            if (e.data.type !== 'trustchain:ready') return;
            setReady(true);
        };
        window.addEventListener('message', handler);
        return () => window.removeEventListener('message', handler);
    }, []);

    const postToPanel = useCallback((payload: Record<string, any>) => {
        iframeRef.current?.contentWindow?.postMessage({
            version: 2,
            source: 'standalone-host-simulator',
            timestamp: new Date().toISOString(),
            ...payload,
        }, window.location.origin);
    }, []);

    useEffect(() => {
        if (!ready) return;
        postToPanel({
            type: 'trustchain:config',
            targetOrigin: window.location.origin,
            instance: 'standalone-simulator',
            context: 'dashboard',
        });
        postToPanel({
            type: 'trustchain:skills',
            skills: [
                { label: 'Сводка рисков', prompt: 'Покажи сводку рисков по верифицированным данным', color: '#06b6d4' },
                { label: 'Проверка цепочки', prompt: 'Проверь целостность TrustChain audit trail', color: '#34d399' },
            ],
        });
        postToPanel({
            type: 'trustchain:workflows',
            workflows: {
                dashboard: [
                    {
                        id: 'simulated_audit',
                        label: 'Симуляция аудита',
                        description: 'Проверка подписей, replay-защиты и хэш-цепочки',
                        requiredTools: ['get_audit_trail', 'verify_audit_proof'],
                    },
                ],
            },
        });
        postToPanel({
            type: 'trustchain:document_mode',
            mode: documentMode,
            label: documentMode === 'level1' ? 'Level 1 (RAG + контент)' : 'Level 2 (Blind Architect)',
            shortLabel: documentMode === 'level1' ? 'L1' : 'L2',
            description: documentMode === 'level1'
                ? 'Доступ к контенту документов разрешен'
                : 'Контент документов заблокирован',
            allowedTools: documentMode === 'level1' ? ['drive_read_content', 'drive_search'] : ['list_documents'],
            blockedTools: documentMode === 'level1' ? [] : ['drive_read_content', 'drive_search'],
        });
    }, [ready, documentMode, postToPanel]);

    return (
        <div className="w-full h-screen bg-slate-950 flex flex-col">
            <div className="px-4 py-3 border-b border-slate-800 flex items-center justify-between">
                <div className="text-sm text-slate-100 font-medium">Standalone Host Simulator</div>
                <div className="flex items-center gap-2">
                    <button
                        className={`px-2 py-1 rounded text-xs ${documentMode === 'level1' ? 'bg-teal-600 text-white' : 'bg-slate-800 text-slate-300'}`}
                        onClick={() => setDocumentMode('level1')}
                    >
                        L1
                    </button>
                    <button
                        className={`px-2 py-1 rounded text-xs ${documentMode === 'level2' ? 'bg-indigo-600 text-white' : 'bg-slate-800 text-slate-300'}`}
                        onClick={() => setDocumentMode('level2')}
                    >
                        L2
                    </button>
                </div>
            </div>
            <iframe
                ref={iframeRef}
                src={`${window.location.origin}/panel?instance=standalone-simulator&context=dashboard&hostOrigin=${encodeURIComponent(window.location.origin)}`}
                className="flex-1 w-full border-0"
                title="TrustChain Panel Simulator"
            />
        </div>
    );
};

const TrustChainAgentApp: React.FC = () => {
    const isHostSimulatorMode = typeof window !== 'undefined'
        && new URLSearchParams(window.location.search).get('host_simulator') === 'true';
    if (isHostSimulatorMode) {
        return <HostSimulatorMode />;
    }

    // ── Chat state (from useChatState hook) ──
    const {
        messages, setMessages,
        inputValue, setInputValue,
        isTyping, setIsTyping,
        activeConversation, setActiveConversation,
        activeArtifactId, setActiveArtifactId,
        dynamicArtifacts, setDynamicArtifacts,
        artifactMaximized, setArtifactMaximized,
        searchQuery, setSearchQuery,
        sessions,
        messagesEndRef, inputRef,
        loadSession, deleteSession: deleteSessionFn, downloadSession, startNewChat,
    } = useChatState([]);

    // ── UI state ──
    const [sidebarOpen, setSidebarOpen] = useState(true);
    const isEmbedded = typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('embed') === 'true';
    const [activeSection, setActiveSection] = useState<'chats' | 'agent' | 'trust'>('chats');
    const [theme, setTheme] = useState<ThemeMode>('light');
    const [showSettings, setShowSettings] = useState(false);
    const [settingsTab, setSettingsTab] = useState<'general' | 'tools' | 'mcp' | 'skills' | 'pro'>('general');
    const [initialToolId, setInitialToolId] = useState<string | undefined>(undefined);
    const [apiKeyInput, setApiKeyInput] = useState(() => localStorage.getItem('tc_api_key') || '');
    const [modelInput, setModelInput] = useState(() => localStorage.getItem('tc_model') || 'google/gemini-2.5-flash');
    const toggleTheme = () => setTheme(t => t === 'dark' ? 'light' : 'dark');

    // ── License state ──
    const [licenseInfo, setLicenseInfo] = useState<LicenseInfo>(() => licensingService.getLicenseInfo());
    const currentTier = licenseInfo.isValid ? licenseInfo.tier : 'community';

    useEffect(() => {
        return licensingService.onChange(setLicenseInfo);
    }, []);

    // ── Backend agent SSE stream state ──
    const [backendStreamSteps, setBackendStreamSteps] = useState<any[]>([]);
    const [isBackendStreaming, setIsBackendStreaming] = useState(false);

    // ── Real Agent ──
    const agent = useAgent();

    // ── Background Task Queue ──
    const taskQueue = useTaskQueue();

    // Auto-initialize agent if API key in localStorage or .env
    useEffect(() => {
        const savedKey = localStorage.getItem('tc_api_key');
        const envKey = import.meta.env?.VITE_OPENAI_API_KEY;
        const apiKey = savedKey || envKey;
        const savedModel = localStorage.getItem('tc_model');
        if (apiKey && !agent.isInitialized) {
            agent.initialize({ apiKey, model: savedModel || 'google/gemini-2.5-flash' });
        }
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    // ── Configure agentCallbacksService on mount ──
    useEffect(() => {
        agentCallbacksService.configure({
            onArtifactCreated: (artifact) => {
                setDynamicArtifacts(prev => ({ ...prev, [artifact.id]: { ...artifact, createdAt: new Date(), version: 1 } }));
                setActiveArtifactId(artifact.id);
            },
            onNotification: (message, severity) => {
                console.log(`[AgentNotification][${severity}]`, message);
            },
            onTaskStatusChange: (taskId, status, progress) => {
                console.log(`[TaskQueue] ${taskId}: ${status} (${progress}%)`);
                taskQueue.refresh();
            },
        });
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    const handleSaveSettings = useCallback(() => {
        localStorage.setItem('tc_api_key', apiKeyInput);
        localStorage.setItem('tc_model', modelInput);
        if (apiKeyInput) {
            agent.initialize({ apiKey: apiKeyInput, model: modelInput });
        }
        setShowSettings(false);
    }, [apiKeyInput, modelInput, agent]);

    // Group tools by category for Agent panel
    const toolsByCategory = useMemo(() => {
        const map: Record<string, AgentTool[]> = {};
        for (const tool of agent.tools) {
            const cat = tool.category || 'Other';
            if (!map[cat]) map[cat] = [];
            map[cat].push(tool);
        }
        return Object.entries(map).sort(([a], [b]) => a.localeCompare(b));
    }, [agent.tools]);

    /** Merge demo + dynamic artifacts for lookup */
    const allArtifacts = useMemo(() => ({ ...DEMO_ARTIFACTS, ...dynamicArtifacts }), [dynamicArtifacts]);
    const activeArtifact = activeArtifactId ? allArtifacts[activeArtifactId] : null;

    /** Detect artifacts created by the real agent in tool result events */
    const extractArtifactsFromEvents = useCallback((events: MessageEvent[]): { artifactIds: string[]; newArtifacts: Record<string, Artifact> } => {
        const artifactIds: string[] = [];
        const newArtifacts: Record<string, Artifact> = {};

        // Track create_artifact tool calls, their names, and their arguments
        const toolCallNames: Record<string, string> = {};
        const toolCallArgs: Record<string, any> = {};
        for (const ev of events) {
            if (ev.type === 'tool_call') {
                toolCallNames[ev.id] = ev.name;
                toolCallArgs[ev.id] = ev.arguments;
            }
            if (ev.type === 'tool_result') {
                // Find the matching tool call name
                const callName = toolCallNames[ev.toolCallId || ''] || '';
                if (callName !== 'create_artifact' && callName !== 'create_file') continue;

                // Parse result — handle both string and object results
                let result: any;
                try {
                    if (typeof ev.result === 'string') {
                        result = JSON.parse(ev.result);
                    } else if (ev.result && typeof ev.result === 'object') {
                        result = ev.result;
                    } else {
                        continue;
                    }
                } catch {
                    // If JSON parse fails, try to extract info from the string
                    if (typeof ev.result === 'string' && ev.result.includes('success')) {
                        // Best-effort: create from tool_call args
                        const args = toolCallArgs[ev.toolCallId || ''];
                        if (args?.filename) {
                            result = { success: true, filename: args.filename, content: args.content };
                        } else {
                            continue;
                        }
                    } else {
                        continue;
                    }
                }

                if (!result?.success && !result?.filename) continue;

                // Get content from result or fall back to tool_call args
                const args = toolCallArgs[ev.toolCallId || ''] || {};
                const artifactContent = result.content || args.content || args.file_text
                    || `Artifact создан: ${result.filename}\nПуть: ${result.path || '/mnt/user-data/outputs/' + result.filename}\nРазмер: ${result.size || 'N/A'}`;

                // Determine artifact type from filename extension
                const ext = (result.filename || '').split('.').pop()?.toLowerCase() || '';
                const typeMap: Record<string, Artifact['type']> = {
                    md: 'document', markdown: 'document',
                    html: 'chart', htm: 'chart',
                    jsx: 'chart', tsx: 'chart',
                    py: 'code', js: 'code', ts: 'code', css: 'code',
                    xlsx: 'table', csv: 'table',
                    pdf: 'report',
                    svg: 'chart',
                    json: 'code',
                    txt: 'document',
                };
                const artType = typeMap[ext] || 'document';

                const artId = `dyn_${result.filename}_${Date.now()}`;
                const art: Artifact = {
                    id: artId,
                    type: artType,
                    title: result.filename,
                    content: artifactContent,
                    createdAt: new Date(),
                    signature: result.signature,
                    version: 1,
                };

                newArtifacts[artId] = art;
                artifactIds.push(artId);
            }
        }

        return { artifactIds, newArtifacts };
    }, []);


    /* Auto-scroll handled by useChatState hook */


    const handleInput = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
        setInputValue(e.target.value);
        e.target.style.height = 'auto';
        e.target.style.height = Math.min(e.target.scrollHeight, 200) + 'px';
    }, []);

    // ── Ask Agent callback (used by ToolManager & SkillsManager) ──
    const handleAskAgent = useCallback((prompt: string) => {
        // Close settings modal
        setShowSettings(false);
        // Prefill chat input and auto-send
        setInputValue(prompt);
        // Small delay so the inputValue state is set before we send
        setTimeout(() => {
            const userMsg: Message = {
                id: `m_${Date.now()}`,
                role: 'user',
                content: prompt,
                timestamp: new Date(),
            };
            setMessages(prev => [...prev, userMsg]);
            setInputValue('');
            setIsTyping(true);
            if (agent.isInitialized) {
                agent.sendMessage(prompt, undefined, messages.slice(-20).map(m => ({ role: m.role, content: m.content }))).then(result => {
                    const events = result?.events || [];
                    const { artifactIds: createdArtifactIds, newArtifacts } = extractArtifactsFromEvents(events);
                    if (Object.keys(newArtifacts).length > 0) {
                        setDynamicArtifacts(prev => ({ ...prev, ...newArtifacts }));
                    }
                    (async () => {
                        let finalText = result?.text || 'Agent processed the request.';
                        let finalSignature: string | undefined;
                        try {
                            const toolSigs = events
                                .filter((ev: any) => ev.type === 'tool_result' && (ev as any).signature)
                                .map((ev: any) => (ev as any).signature);
                            const proof = await trustchainService.signFinalResponse(finalText, toolSigs, { mode: 'standalone' });
                            finalSignature = proof.envelope.signature;
                            finalText += `\n\n> ✅ Final Response Signed · key: \`${proof.envelope.key_id}\` · seq: \`${proof.envelope.sequence}\``;
                        } catch {
                            // ignore signing failures
                        }
                        const assistantMsg: Message = {
                            id: `m_${Date.now() + 1}`,
                            role: 'assistant',
                            content: finalText,
                            timestamp: new Date(),
                            signature: finalSignature,
                            verified: !!finalSignature,
                            ...(createdArtifactIds.length > 0 && { artifactIds: createdArtifactIds }),
                        };
                        setMessages(prev => [...prev, assistantMsg]);
                        setIsTyping(false);
                        if (createdArtifactIds.length > 0) {
                            setActiveArtifactId(createdArtifactIds[0]);
                        }
                    })();
                });
            } else {
                setIsTyping(false);
            }
        }, 100);
    }, [agent]);

    const handleSend = useCallback(async () => {
        if (!inputValue.trim()) return;
        const text = inputValue.trim();

        const userMsg: Message = {
            id: `m_${Date.now()}`,
            role: 'user',
            content: text,
            timestamp: new Date(),
        };
        setMessages(prev => [...prev, userMsg]);
        setInputValue('');
        setIsTyping(true);
        if (inputRef.current) inputRef.current.style.height = 'auto';

        // Auto-assign conversation ID on first message in a new chat
        if (!activeConversation) {
            setActiveConversation(`chat_${Date.now()}`);
        }

        // ── License tier check ──
        const freshLicense = licensingService.getLicenseInfo();
        const effectiveTier = freshLicense.isValid ? freshLicense.tier : 'community';

        if (agent.isInitialized) {
            // ── Real agent execution ──
            // Start a session on first message (AI Studio pattern)
            if (messages.length === 0) {
                chatHistoryService.startSession('TrustChain Agent', 'openai');
            }

            // Save user message to persistent history
            chatHistoryService.addMessage({ role: 'user', content: text, timestamp: new Date() });

            // ── Start backend agent run + SSE stream ──
            setBackendStreamSteps([]);
            setIsBackendStreaming(true);
            try {
                // Fire and forget — the agent runs server-side
                dockerAgentService.runAgent({
                    instruction: text,
                    model: modelInput,
                    max_iterations: effectiveTier === 'enterprise' ? 25 : effectiveTier === 'pro' ? 15 : 10,
                }).catch(() => { /* backend may be unavailable */ });

                // Connect SSE stream for real-time reasoning visualization
                const es = dockerAgentService.streamAgent((event: AgentStreamEvent) => {
                    if (event.type === 'thinking') {
                        setBackendStreamSteps(prev => [...prev, {
                            id: `sse_${Date.now()}`,
                            type: 'planning',
                            label: event.message || `Iteration ${event.iteration}`,
                            detail: event.message,
                            latencyMs: 0,
                        }]);
                    } else if (event.type === 'tool_call') {
                        setBackendStreamSteps(prev => [...prev, {
                            id: `sse_tc_${Date.now()}`,
                            type: 'tool',
                            label: event.tool || 'tool',
                            toolName: event.tool,
                            args: event.args,
                            detail: `Executing ${event.tool}`,
                            latencyMs: 0,
                            signed: false,
                        }]);
                    } else if (event.type === 'tool_result') {
                        setBackendStreamSteps(prev => [...prev, {
                            id: `sse_tr_${Date.now()}`,
                            type: 'tool',
                            label: `${event.tool} result`,
                            toolName: event.tool,
                            result: event.result,
                            detail: event.result?.substring(0, 150),
                            latencyMs: 0,
                            signed: !!event.signature,
                            signature: event.signature,
                        }]);
                    } else if (event.type === 'complete' || event.type === 'error') {
                        setIsBackendStreaming(false);
                        es?.close();
                    }
                });
            } catch {
                setIsBackendStreaming(false);
            }

            try {
                // Pass actual conversation history (excluding temp messages)
                const chatHistory = messages
                    .filter(m => (m.role as string) !== 'assistant_temp')
                    .map(m => ({ role: m.role, content: m.content }));
                const result = await agent.sendMessage(text, undefined, chatHistory);
                const events = result?.events || [];

                // Extract artifacts created during execution
                const { artifactIds: createdArtifactIds, newArtifacts } = extractArtifactsFromEvents(events);

                // Register new dynamic artifacts
                if (Object.keys(newArtifacts).length > 0) {
                    setDynamicArtifacts(prev => ({ ...prev, ...newArtifacts }));
                }

                // ── Post-process: TrustChain verification badges via shared utility ──
                const { content: processedContent, signedResults, hasVerification } = postProcessAgentResponse(
                    result?.text || 'Агент обработал запрос, но не вернул текстовый ответ.',
                    events as any[],
                );
                let finalText = processedContent;
                let finalSignature: string | undefined;
                try {
                    const toolSigs = signedResults.map(sr => sr.signature);
                    const proof = await trustchainService.signFinalResponse(finalText, toolSigs, { mode: 'standalone' });
                    finalSignature = proof.envelope.signature;
                    finalText += `\n\n> ✅ Final Response Signed · key: \`${proof.envelope.key_id}\` · seq: \`${proof.envelope.sequence}\``;
                } catch {
                    // do not block response if signing failed
                }

                // Append license tier info
                if (effectiveTier !== 'community') {
                    finalText += `\n\n> 🔑 License: **${effectiveTier.toUpperCase()}** · ${freshLicense.orgName || 'Active'} · ${freshLicense.daysRemaining}d remaining`;
                }

                const assistantMsg: Message = {
                    id: `m_${Date.now() + 1}`,
                    role: 'assistant',
                    content: finalText,
                    timestamp: new Date(),
                    signature: finalSignature,
                    verified: !!finalSignature,
                    ...(createdArtifactIds.length > 0 && { artifactIds: createdArtifactIds }),
                    executionSteps: (() => {
                        // ── Tier mapping for tool names ──
                        const TOOL_TIERS: Record<string, 'oss' | 'pro' | 'enterprise'> = {
                            tc_sign: 'oss', tc_verify_chain: 'oss', tc_get_audit_trail: 'oss',
                            tc_get_stats: 'oss', tc_security_scan: 'oss', tc_git_diff: 'oss',
                            tc_execution_graph: 'pro', tc_analytics_snapshot: 'pro',
                            tc_policy_evaluate: 'pro', tc_kms_keys: 'pro', tc_kms_rotate: 'pro',
                            tc_compliance_report: 'enterprise', tc_tsa_timestamp: 'enterprise',
                            tc_tsa_verify: 'enterprise', tc_airgap_status: 'enterprise',
                        };
                        const getTier = (name: string) => TOOL_TIERS[name] || (name.startsWith('tc_') ? 'oss' : undefined);

                        // ── Merge tool_call + tool_result pairs ──
                        const merged: any[] = [];
                        const callMap = new Map<string, any>(); // toolCallId → call event

                        for (const ev of events) {
                            if (ev.type === 'thinking') {
                                merged.push({
                                    id: ev.id,
                                    type: 'planning' as const,
                                    label: ev.title || 'Reasoning',
                                    detail: ev.content,
                                    latencyMs: 0,
                                });
                            } else if (ev.type === 'tool_call') {
                                callMap.set(ev.id, ev);
                                // Don't push yet — wait for matching result
                            } else if (ev.type === 'tool_result') {
                                const callEv = callMap.get((ev as any).toolCallId);
                                const toolName = callEv?.name || 'unknown';
                                const tier = getTier(toolName);
                                const latencyMs = callEv?.timestamp && ev.timestamp
                                    ? new Date(ev.timestamp).getTime() - new Date(callEv.timestamp).getTime()
                                    : 0;
                                const result = ev.result;
                                const backendSig = typeof result === 'object' && result?.__tc_backend_signature;
                                const backendVerified = typeof result === 'object' && result?.__tc_backend_verified;

                                merged.push({
                                    id: ev.id,
                                    type: 'tool' as const,
                                    label: toolName,
                                    toolName,
                                    args: callEv?.arguments,
                                    detail: typeof result === 'string'
                                        ? result?.substring(0, 150)
                                        : JSON.stringify(result)?.substring(0, 150),
                                    latencyMs: Math.max(0, latencyMs),
                                    signed: !!(ev as any).signature || !!backendSig,
                                    signature: (ev as any).signature || backendSig,
                                    backendVerified: !!backendVerified,
                                    ...(tier && { tier }),
                                });

                                // Remove from map so unmatched calls are pushed at the end
                                if (callEv) callMap.delete(callEv.id);
                            }
                        }

                        // Push any unmatched tool_call events (still running)
                        for (const [, callEv] of callMap) {
                            const toolName = callEv.name;
                            merged.push({
                                id: callEv.id,
                                type: 'tool' as const,
                                label: toolName,
                                toolName,
                                args: callEv.arguments,
                                detail: `Executing ${toolName}...`,
                                latencyMs: 0,
                                signed: false,
                                ...(getTier(toolName) && { tier: getTier(toolName) }),
                            });
                        }

                        // Auto-generate "Artifacts" summary step
                        const artifactSteps = merged.filter(s => s.toolName === 'create_artifact');
                        if (artifactSteps.length > 0) {
                            merged.push({
                                id: `artifacts_summary_${Date.now()}`,
                                type: 'planning' as const,
                                label: `${artifactSteps.length} Artifact${artifactSteps.length > 1 ? 's' : ''} Generated`,
                                detail: artifactSteps.map(s => s.args?.identifier || s.args?.title || 'artifact').join(', '),
                                latencyMs: 0,
                            });
                        }

                        return merged;
                    })(),
                };
                setMessages(prev => [...prev, assistantMsg]);
                setIsTyping(false);
                setIsBackendStreaming(false);

                // Save assistant response to persistent history
                chatHistoryService.addMessage({
                    role: 'assistant',
                    content: assistantMsg.content,
                    timestamp: assistantMsg.timestamp,
                    executionSteps: assistantMsg.executionSteps,
                    signature: assistantMsg.signature,
                    verified: assistantMsg.verified,
                    artifactIds: assistantMsg.artifactIds,
                });

                // Auto-open the first created artifact in the right panel
                if (createdArtifactIds.length > 0) {
                    setActiveArtifactId(createdArtifactIds[0]);
                }
            } catch (agentError: any) {
                // ── Show error to user instead of silent failure ──
                const errMsg = agentError?.message || String(agentError);
                console.error('[TrustChain] Agent execution error:', agentError);
                const errorResponse: Message = {
                    id: `m_err_${Date.now()}`,
                    role: 'assistant',
                    content: `⚠️ **Agent Error**\n\n${errMsg}\n\n> Check Settings → API Key and Model configuration. Make sure the backend is running.`,
                    timestamp: new Date(),
                };
                setMessages(prev => [...prev, errorResponse]);
                setIsTyping(false);
                setIsBackendStreaming(false);
            }
        } else {
            // ── Fallback: no agent configured ──
            setTimeout(() => {
                const tierLabel = effectiveTier !== 'community' ? ` (License: ${effectiveTier.toUpperCase()})` : '';
                const assistantMsg: Message = {
                    id: `m_${Date.now() + 1}`,
                    role: 'assistant',
                    content: `**Agent not connected.** Open Settings (gear icon) and enter your OpenAI/OpenRouter API key to enable real agent execution.${tierLabel}\n\nOnce configured, I can execute ${agent.tools.length || '50+'} tools including code analysis, web search, file operations, and more.`,
                    timestamp: new Date(),
                };
                setMessages(prev => [...prev, assistantMsg]);
                setIsTyping(false);
            }, 500);
        }
    }, [inputValue, agent, modelInput]);

    const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };

    const isNewChat = messages.length === 0;

    return (
        <div data-theme={theme} className="h-screen w-screen flex tc-app overflow-hidden">

            {/* ═══ SIDEBAR ═══ */}
            {!isEmbedded && (
                sidebarOpen ? (
                    <ChatSidebar
                        activeConversation={activeConversation}
                        setActiveConversation={setActiveConversation}
                        messages={messages}
                        setMessages={setMessages}
                        activeSection={activeSection}
                        setActiveSection={setActiveSection}
                        searchQuery={searchQuery}
                        setSearchQuery={setSearchQuery}
                        activeArtifactId={activeArtifactId}
                        setActiveArtifactId={setActiveArtifactId}
                        setSidebarOpen={setSidebarOpen}
                        setShowSettings={setShowSettings}
                        setSettingsTab={setSettingsTab}
                        setInitialToolId={setInitialToolId}
                        agent={agent}
                        toolsByCategory={toolsByCategory}
                        demoMessages={DEMO_MESSAGES}
                        sessions={sessions}
                        onLoadSession={loadSession}
                        onDeleteSession={deleteSessionFn}
                        onDownloadSession={downloadSession}
                        onNewChat={startNewChat}
                    />
                ) : (
                    /* ── Collapsed sidebar strip ── */
                    <div
                        className="shrink-0 w-[36px] border-r tc-sidebar flex flex-col items-center cursor-pointer hover:bg-white/5 transition-colors"
                        onClick={() => setSidebarOpen(true)}
                        title="Expand sidebar"
                    >
                        <div className="mt-4 mb-2">
                            <div className="w-7 h-7 tc-logo rounded-lg flex items-center justify-center shadow-md">
                                <Shield size={14} className="text-white" />
                            </div>
                        </div>
                        <div className="flex-1 flex items-center">
                            <ChevronRight size={14} className="tc-text-muted" />
                        </div>
                    </div>
                )
            )}

            {/* ═══ CHAT (center) ═══ */}
            <div className={`flex-1 flex flex-col min-w-0 w-0 overflow-hidden ${activeArtifact && !artifactMaximized ? '' : ''}`}>
                {!isEmbedded && <ChatHeader
                    sidebarOpen={sidebarOpen}
                    setSidebarOpen={setSidebarOpen}
                    activeConversation={activeConversation}
                    theme={theme}
                    toggleTheme={toggleTheme}
                    agent={agent}
                    setShowSettings={setShowSettings}
                />}

                {/* Content area — split when artifact is open */}
                <div className="flex-1 flex min-h-0 min-w-0 overflow-hidden">
                    {/* Chat column — messages + input stacked vertically */}
                    <div className={`flex flex-col min-w-0 overflow-hidden ${activeArtifact && !artifactMaximized ? 'w-[45%] min-w-[360px]' : 'flex-1'}
                        ${artifactMaximized ? 'hidden' : ''}`}>
                        <ChatArea
                            messages={messages}
                            isNewChat={isNewChat}
                            isTyping={isTyping}
                            activeArtifactId={activeArtifactId}
                            allArtifacts={allArtifacts}
                            artifactMaximized={artifactMaximized}
                            activeArtifact={activeArtifact}
                            messagesEndRef={messagesEndRef}
                            inputRef={inputRef}
                            setActiveArtifactId={setActiveArtifactId}
                            setInputValue={setInputValue}
                            streamingEvents={agent.streamingEvents}
                            streamingText={agent.streamingText}
                        />
                        <InputPanel
                            inputValue={inputValue}
                            setInputValue={setInputValue}
                            inputRef={inputRef}
                            isTyping={isTyping}
                            onSend={handleSend}
                            onKeyDown={handleKeyDown}
                            onInput={handleInput}
                        />
                    </div>

                    {/* ═══ ARTIFACT PANEL (right) ═══ */}
                    {activeArtifact && (
                        <div className={`${artifactMaximized ? 'flex-1' : 'w-[55%]'} min-w-[400px]`}>
                            <ArtifactsPanel
                                artifact={activeArtifact}
                                onClose={() => { setActiveArtifactId(null); setArtifactMaximized(false); }}
                                isMaximized={artifactMaximized}
                                onToggleMaximize={() => setArtifactMaximized(!artifactMaximized)}
                            />
                        </div>
                    )}
                </div>
            </div>

            {/* ═══ SETTINGS MODAL ═══ */}
            {showSettings && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"
                    onClick={(e) => { if (e.target === e.currentTarget) setShowSettings(false); }}>
                    <div className={`tc-surface border tc-border-light rounded-2xl shadow-2xl max-h-[80vh] overflow-auto transition-all duration-300 ${settingsTab === 'tools' || settingsTab === 'mcp' || settingsTab === 'skills' || settingsTab === 'pro' ? 'w-[600px]' : 'w-[460px]'}`}>
                        {/* Header */}
                        <div className="flex items-center justify-between p-5 border-b tc-border">
                            <div className="flex items-center gap-2">
                                <Settings size={18} className="tc-text-muted" />
                                <h3 className="text-base font-semibold tc-text-heading">Agent Settings</h3>
                            </div>
                            <button onClick={() => setShowSettings(false)}
                                className="tc-text-muted hover:tc-text p-1 rounded-lg tc-btn-hover">
                                <X size={16} />
                            </button>
                        </div>

                        {/* Tabs */}
                        <div className="flex border-b tc-border">
                            <button
                                onClick={() => setSettingsTab('general')}
                                className={`flex-1 px-4 py-2.5 text-xs font-semibold transition-colors
                                    ${settingsTab === 'general'
                                        ? 'tc-text border-b-2 border-blue-500'
                                        : 'tc-text-muted hover:tc-text'}`}
                            >
                                General
                            </button>
                            <button
                                onClick={() => setSettingsTab('tools')}
                                className={`flex-1 px-4 py-2.5 text-xs font-semibold transition-colors
                                    ${settingsTab === 'tools'
                                        ? 'tc-text border-b-2 border-blue-500'
                                        : 'tc-text-muted hover:tc-text'}`}
                            >
                                Tools ({agent.tools.length || '—'})
                            </button>
                            <button
                                onClick={() => setSettingsTab('mcp')}
                                className={`flex-1 px-4 py-2.5 text-xs font-semibold transition-colors
                                    ${settingsTab === 'mcp'
                                        ? 'tc-text border-b-2 border-blue-500'
                                        : 'tc-text-muted hover:tc-text'}`}
                            >
                                MCP Servers
                            </button>
                            <button
                                onClick={() => setSettingsTab('skills')}
                                className={`flex-1 px-4 py-2.5 text-xs font-semibold transition-colors
                                    ${settingsTab === 'skills'
                                        ? 'tc-text border-b-2 border-violet-500'
                                        : 'tc-text-muted hover:tc-text'}`}
                            >
                                Skills (70)
                            </button>
                            <button
                                onClick={() => setSettingsTab('pro')}
                                className={`flex-1 px-4 py-2.5 text-xs font-semibold transition-colors
                                    ${settingsTab === 'pro'
                                        ? 'tc-text border-b-2 border-amber-500'
                                        : 'tc-text-muted hover:tc-text'}`}
                            >
                                ⚡ Pro
                            </button>
                        </div>

                        {/* Body */}
                        <div className="p-5 space-y-5">

                            {settingsTab === 'tools' ? (
                                <ToolManager
                                    enabledTools={agent.enabledTools}
                                    onToggleTool={agent.setToolEnabled}
                                    onBulkEnable={agent.setAllToolsEnabled}
                                    onResetDefaults={agent.resetToolsToDefaults}
                                    initialToolId={initialToolId}
                                    onAskAgent={handleAskAgent}
                                />
                            ) : settingsTab === 'mcp' ? (
                                <MCPManager />
                            ) : settingsTab === 'skills' ? (
                                <SkillsManager onAskAgent={handleAskAgent} />
                            ) : settingsTab === 'pro' ? (
                                <ProSettingsPanel />
                            ) : (
                                <>
                                    {/* Status */}
                                    <div className="flex items-center gap-3 p-3 tc-surface border tc-border-light rounded-xl">
                                        <div className={`w-3 h-3 rounded-full ${agent.status === 'ready' ? 'bg-emerald-500' :
                                            agent.status === 'thinking' ? 'bg-amber-500 animate-pulse' :
                                                agent.status === 'error' ? 'bg-red-500' : 'bg-gray-400'
                                            }`} />
                                        <div className="flex-1">
                                            <div className="text-sm tc-text font-medium capitalize">{agent.status}</div>
                                            <div className="text-[11px] tc-text-muted">
                                                {agent.isInitialized
                                                    ? `${agent.tools.length} tools available`
                                                    : 'Enter API key to activate agent'}
                                            </div>
                                        </div>
                                        {agent.error && (
                                            <div className="text-[11px] text-red-400 max-w-[200px] truncate" title={agent.error}>
                                                {agent.error}
                                            </div>
                                        )}
                                    </div>

                                    {/* API Key */}
                                    <div>
                                        <label className="block text-xs font-medium tc-text-muted mb-1.5">
                                            OpenAI / OpenRouter API Key
                                        </label>
                                        <input
                                            type="password"
                                            value={apiKeyInput}
                                            onChange={(e) => setApiKeyInput(e.target.value)}
                                            placeholder="sk-... or your OpenRouter key"
                                            className="w-full px-3 py-2 text-sm tc-surface border tc-border-light rounded-xl 
                                        tc-text font-mono focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                                        />
                                        <p className="text-[10px] tc-text-muted mt-1">
                                            Stored locally in your browser. Never sent to third parties.
                                        </p>
                                    </div>

                                    {/* Model */}
                                    <div>
                                        <label className="block text-xs font-medium tc-text-muted mb-1.5">
                                            Model
                                        </label>
                                        <select
                                            value={modelInput}
                                            onChange={(e) => setModelInput(e.target.value)}
                                            className="w-full px-3 py-2 text-sm tc-surface border tc-border-light rounded-xl 
                                        tc-text focus:outline-none focus:ring-2 focus:ring-blue-500/30"
                                        >
                                            <optgroup label="Google Gemini">
                                                <option value="google/gemini-2.5-flash">Gemini 2.5 Flash</option>
                                                <option value="google/gemini-3-flash-preview">Gemini 3 Flash (preview)</option>
                                                <option value="google/gemini-2.5-pro">Gemini 2.5 Pro</option>
                                                <option value="google/gemini-3-pro-preview">Gemini 3 Pro (preview)</option>
                                                <option value="google/gemini-2.5-flash-lite">Gemini 2.5 Flash Lite</option>
                                            </optgroup>
                                            <optgroup label="OpenAI">
                                                <option value="openai/gpt-5.2">GPT-5.2</option>
                                                <option value="openai/gpt-5.1">GPT-5.1</option>
                                                <option value="openai/gpt-5-mini">GPT-5 Mini</option>
                                                <option value="openai/gpt-5-nano">GPT-5 Nano</option>
                                                <option value="openai/o3">o3</option>
                                                <option value="openai/gpt-4.1">GPT-4.1</option>
                                                <option value="openai/gpt-4.1-mini">GPT-4.1 Mini</option>
                                                <option value="openai/gpt-4o">GPT-4o</option>
                                            </optgroup>
                                            <optgroup label="Anthropic">
                                                <option value="anthropic/claude-opus-4.6">Claude Opus 4.6</option>
                                                <option value="anthropic/claude-sonnet-4.5">Claude Sonnet 4.5</option>
                                                <option value="anthropic/claude-sonnet-4">Claude Sonnet 4</option>
                                                <option value="anthropic/claude-haiku-4.5">Claude Haiku 4.5</option>
                                            </optgroup>
                                            <optgroup label="DeepSeek">
                                                <option value="deepseek/deepseek-v3.2">DeepSeek V3.2</option>
                                                <option value="deepseek/deepseek-r1-0528">DeepSeek R1</option>
                                                <option value="deepseek/deepseek-chat-v3.1">DeepSeek Chat v3.1</option>
                                            </optgroup>
                                        </select>
                                    </div>

                                    {/* Tools count */}
                                    {agent.isInitialized && (
                                        <div className="p-3 tc-surface border tc-border-light rounded-xl">
                                            <div className="text-[10px] font-semibold tc-text-muted uppercase tracking-wider mb-1">
                                                Loaded Tools
                                            </div>
                                            <div className="text-2xl font-bold tc-text-heading">{agent.tools.length}</div>
                                            <div className="text-[11px] tc-text-muted">
                                                across {toolsByCategory.length} categories
                                            </div>
                                        </div>
                                    )}
                                </>)}
                        </div>

                        {/* Footer */}
                        <div className="flex items-center justify-end gap-2 p-5 border-t tc-border">
                            <button onClick={() => setShowSettings(false)}
                                className="px-4 py-2 text-sm tc-text-muted hover:tc-text rounded-xl tc-btn-hover transition-colors">
                                Cancel
                            </button>
                            <button onClick={handleSaveSettings}
                                className="px-4 py-2 text-sm text-white rounded-xl transition-colors
                                    bg-gradient-to-r from-blue-500 to-violet-500 hover:from-blue-600 hover:to-violet-600
                                    shadow-lg shadow-blue-500/20">
                                Save & Connect
                            </button>
                        </div>
                    </div>
                </div>
            )}
            {/* ═══ CHAIN STATUS BAR ═══ */}
            {!isEmbedded && <ChainStatusBar />}
        </div>
    );
};

export default TrustChainAgentApp;
